x-othentic-cli: &othentic-cli
  env_file:
    - .env
  build:
    context: .
    dockerfile: ./Dockerfile

services:
  aggregator:
    <<: *othentic-cli
    command: ["node", "aggregator", "--json-rpc"]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_AGGREGATOR:-495f8ce0cec433ba12459445a2eb5c8653459621d8d1a2aca86993aeb155de22}
    ports:
      - "8545:8545"
      - "9876:9876"
    networks:
      p2p:
        ipv4_address: 10.8.0.69
  attester-1:
    <<: *othentic-cli
    command: [
      "node",
      "attester",
      "/ip4/10.8.0.69/tcp/9876/p2p/${OTHENTIC_BOOTSTRAP_ID}",
      "--avs-webapi",
      "http://10.8.0.42",
    ]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_ATTESTER1:-495f8ce0cec433ba12459445a2eb5c8653459621d8d1a2aca86993aeb155de22}
      - TASK_PERFORMER=0x0000000000000000000000000000000000000000
    depends_on:
      aggregator:
        condition: service_started
    networks:
      p2p:
        ipv4_address: 10.8.0.2
  attester-2:
    <<: *othentic-cli
    command: [
      "node",
      "attester",
      "/ip4/10.8.0.69/tcp/9876/p2p/${OTHENTIC_BOOTSTRAP_ID}",
      "--avs-webapi",
      "http://10.8.0.42",
    ]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_ATTESTER1:-411f50fb317d5633512077040cd11135854a6946d4b7e43a5d541116256e2e76}
      - TASK_PERFORMER=0x0000000000000000000000000000000000000000
    depends_on:
      aggregator:
        condition: service_started
    networks:
      p2p:
        ipv4_address: 10.8.0.3
  attester-3:
    <<: *othentic-cli
    command: [
      "node",
      "attester",
      "/ip4/10.8.0.69/tcp/9876/p2p/${OTHENTIC_BOOTSTRAP_ID}",
      "--avs-webapi",
      "http://10.8.0.42",
    ]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_ATTESTER3:-9ccde5c7f98eff2182640f1bfcc4f0cf10cb3d8eec034398743b4b26581432f4}
      - TASK_PERFORMER=0x0000000000000000000000000000000000000000
    depends_on:
      aggregator:
        condition: service_started
    networks:
      p2p:
        ipv4_address: 10.8.0.4
  
  validation-service:
    build:
      context: ./validation-service
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "4002:4002"
    networks:
      p2p:
        ipv4_address: 10.8.0.42
  execution-service:
    build:
      context: ./execution-service
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "4003:4003"
    networks:
      p2p:
        ipv4_address: 10.8.0.43
    depends_on:
      aggregator:
          condition: service_started
  task-performer:
    build:
        context: ./task-performer
        dockerfile: ./Dockerfile
    environment:
      - OTHENTIC_CLIENT_RPC_ADDRESS=http://10.8.0.69:8545
      - PRIVATE_KEY=${PRIVATE_KEY_PERFORMER:-495f8ce0cec433ba12459445a2eb5c8653459621d8d1a2aca86993aeb155de22}
    env_file:
      - .env
    depends_on:
      execution-service:
        condition: service_started
    ports:
      - "5002:5002"
    networks:
      p2p:
        ipv4_address: 10.8.0.44

networks:
  p2p:
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.0.0/16
          gateway: 10.8.0.1